# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20171026_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
